# Generated by Django 5.0.7 on 2024-07-29 09:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Класс')),
                ('spells', models.JSONField(blank=True, null=True, verbose_name='Заклинания')),
                ('hp_dice', models.IntegerField(verbose_name='Дайсы очков жизни')),
                ('saving_throws', models.CharField(verbose_name='Спасброски')),
                ('armor', models.TextField(verbose_name='Броня')),
                ('weapons', models.TextField(verbose_name='Оружие')),
                ('tools', models.TextField(verbose_name='Инструменты')),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None, verbose_name='Навыки')),
                ('spellcasting_ability', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Расса')),
                ('size', models.FloatField(verbose_name='Размер')),
                ('speed', models.FloatField(verbose_name='Скорость')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('languages', models.CharField(blank=True, max_length=255, verbose_name='Языки')),
                ('abilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None, verbose_name='Способности')),
                ('abil_score_inc', models.JSONField(blank=True, null=True, verbose_name='Очки усиления')),
            ],
        ),
    ]
