# Generated by Django 5.1 on 2024-09-12 12:28

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Класс')),
                ('hp_dice', models.IntegerField(verbose_name='Дайсы очков жизни')),
                ('saving_throws', models.CharField(verbose_name='Спасброски')),
                ('armor', models.TextField(verbose_name='Броня')),
                ('weapons', models.TextField(verbose_name='Оружие')),
                ('tools', models.TextField(verbose_name='Инструменты')),
                ('skills', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None, verbose_name='Навыки')),
                ('spellcasting_ability', models.CharField(blank=True)),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Расса')),
                ('size', models.FloatField(verbose_name='Размер')),
                ('speed', models.FloatField(verbose_name='Скорость')),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('languages', models.CharField(blank=True, max_length=255, verbose_name='Языки')),
                ('abilities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), blank=True, size=None, verbose_name='Способности')),
                ('abil_score_inc', models.JSONField(blank=True, null=True, verbose_name='Очки усиления')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='ClassInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('table', models.TextField(blank=True, verbose_name='Таблица уровней')),
                ('description', models.TextField(verbose_name='Описание')),
                ('character_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='character.characterclass', verbose_name='Класс')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=25, verbose_name='Имя персонажа')),
                ('background', models.CharField(blank=True, max_length=25, verbose_name='Предыстория')),
                ('alignment', models.CharField(blank=True, max_length=25, verbose_name='Мировоззрение')),
                ('player_name', models.CharField(blank=True, max_length=25, verbose_name='Имя игрока')),
                ('level', models.IntegerField(blank=True, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)], verbose_name='Уровень')),
                ('experience', models.IntegerField(blank=True, verbose_name='Опыт')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_class', to='character.characterclass', verbose_name='Класс')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_race', to='character.race', verbose_name='Раса')),
            ],
        ),
        migrations.CreateModel(
            name='RaceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='character.race', verbose_name='Расса')),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('spell_type', models.CharField(default='Очарование', verbose_name='Тип')),
                ('time', models.CharField(blank=True, verbose_name='Время накладывания')),
                ('distance', models.CharField(blank=True, verbose_name='Дистанция')),
                ('components', models.CharField(blank=True, verbose_name='Компоненты')),
                ('duration', models.CharField(blank=True, verbose_name='Длительность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('character_class', models.ManyToManyField(related_name='spells', to='character.characterclass', verbose_name='Класс')),
            ],
        ),
    ]
