# Generated by Django 5.0.7 on 2024-07-30 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='spells',
        ),
        migrations.CreateModel(
            name='ClassInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('character_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='character.characterclass', verbose_name='Класс')),
            ],
        ),
        migrations.CreateModel(
            name='RaceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('race', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='character.race', verbose_name='Расса')),
            ],
        ),
        migrations.CreateModel(
            name='Spells',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('time', models.CharField(blank=True, verbose_name='Время накладывания')),
                ('distance', models.IntegerField(blank=True, verbose_name='Дистанция')),
                ('components', models.CharField(blank=True, verbose_name='Компоненты')),
                ('duration', models.CharField(blank=True, verbose_name='Длительность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('character_class', models.ManyToManyField(related_name='spells', to='character.characterclass', verbose_name='Класс')),
            ],
        ),
    ]
