# Generated by Django 5.1 on 2024-09-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_character_characteristics_character_modifiers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='skills',
        ),
        migrations.AddField(
            model_name='character',
            name='proficiency_bonus',
            field=models.IntegerField(blank=True, default=2, verbose_name='Бонус мастерства'),
        ),
        migrations.AddField(
            model_name='character',
            name='saving_throws',
            field=models.JSONField(blank=True, null=True, verbose_name='Спасброски'),
        ),
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.JSONField(blank=True, null=True, verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='characterclass',
            name='spellcasting_ability',
            field=models.CharField(blank=True, verbose_name='Базовая характеристика'),
        ),
    ]
