# Generated by Django 5.0.7 on 2024-07-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0002_remove_characterclass_spells_classinformation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
    ]
