# Generated by Django 5.0.7 on 2024-07-31 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_spells_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells',
            name='spell_type',
            field=models.CharField(default='Очарование', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='spells',
            name='distance',
            field=models.CharField(blank=True, verbose_name='Дистанция'),
        ),
    ]
