# Generated by Django 5.1 on 2024-09-18 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0003_remove_characterclass_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='skills',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='Навыки'),
        ),
    ]
