# Generated by Django 5.1 on 2024-09-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_characterclass_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterclass',
            name='skills',
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('about', models.TextField(verbose_name='Описание')),
                ('character_class', models.ManyToManyField(related_name='skills', to='character.characterclass', verbose_name='Класс')),
            ],
        ),
    ]
