# Generated by Django 5.0.7 on 2024-08-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0004_spells_spell_type_alter_spells_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
    ]
