# Generated by Django 5.0.7 on 2024-08-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_alter_spells_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterclass',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='race',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
    ]
