# Generated by Django 5.1 on 2024-09-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0006_remove_character_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(related_name='character', to='character.skills', verbose_name='Навыки'),
        ),
        migrations.AddField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(related_name='character', to='character.spells', verbose_name='Заклинания'),
        ),
    ]
