# Generated by Django 5.1 on 2024-09-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_character_skills_character_spells'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='characterclass',
            name='quantity_of_spells',
            field=models.JSONField(blank=True, null=True, verbose_name='Количество заклинаний от уровня'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(null=True, related_name='character', to='character.spells', verbose_name='Заклинания'),
        ),
    ]
