# Generated by Django 5.0.7 on 2024-08-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0007_characterclass_slug_race_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='race',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
