# Generated by Django 5.0.7 on 2024-08-05 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_alter_characterclass_slug_alter_race_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classinformation',
            name='character_class',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='character.characterclass', verbose_name='Класс'),
        ),
    ]
