# Generated by Django 5.1 on 2024-09-26 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0008_alter_skills_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('type', models.CharField(max_length=35, verbose_name='Тип')),
                ('armor_class', models.CharField(max_length=20, verbose_name='Класс защиты')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('stealth_interference', models.BooleanField(default=True, verbose_name='Помеха на Скрытность')),
                ('requirement_strength', models.IntegerField(verbose_name='Требование к Силе')),
                ('on_off', models.CharField(verbose_name='Надевание/Снятие')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название')),
                ('type', models.CharField(max_length=25, verbose_name='Тип')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
                ('damage', models.CharField(max_length=5, verbose_name='Урон')),
                ('damage_type', models.CharField(max_length=25, verbose_name='Тип урона')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('property', models.JSONField(blank=True, null=True, verbose_name='Свойства')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
