# Generated by Django 5.0.7 on 2024-08-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0009_alter_classinformation_character_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='classinformation',
            name='table',
            field=models.TextField(blank=True, verbose_name='Таблица уровней'),
        ),
    ]
