# Generated by Django 5.1 on 2024-10-25 19:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_character_armor_character_money_character_weapons_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='weapons',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='character',
            name='armor',
            field=models.ManyToManyField(blank=True, related_name='character', to='character.armor', verbose_name='Доспехи'),
        ),
        migrations.AlterField(
            model_name='character',
            name='money',
            field=models.IntegerField(default=9000, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Деньги(медные монеты)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(related_name='character', to='character.spells', verbose_name='Заклинания'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, related_name='character', to='character.weapons', verbose_name='Оружие'),
        ),
    ]
