# Generated by Django 5.1 on 2024-08-13 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0010_classinformation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceinformation',
            name='race',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='character.race', verbose_name='Расса'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Имя')),
                ('characteristics', models.JSONField(default=dict)),
                ('ch_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character', to='character.characterclass', verbose_name='Класс')),
            ],
        ),
    ]
