# Generated by Django 5.1 on 2024-10-29 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0011_alter_armor_options_alter_weapons_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.CharField(blank=True, choices=[('lawful good', 'Упорядоченно добрый'), ('neutral good', 'Добрый'), ('chaotic good', 'Хаотично добрый'), ('lawful neutral', 'Упорядоченный'), ('true neutral', 'Истинно нейтральный'), ('chaotic neutral', 'Хаотичный'), ('lawful evil', 'Упорядоченно злой'), ('neutral evil', 'Злой'), ('chaotic evil', 'Хаотично злой'), ('unaligned', 'Вне мировоззрения')], max_length=25, null=True, verbose_name='Мировоззрение'),
        ),
        migrations.AlterField(
            model_name='character',
            name='armor',
            field=models.ManyToManyField(blank=True, null=True, related_name='character', to='character.armor', verbose_name='Доспехи'),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(blank=True, choices=[('artist', 'Артист'), ('homeless', 'Безпризорник'), ('noble', 'Благородный'), ('guild craftsman', 'Гидьдейский ремесленник'), ('sailor', 'Моряк'), ('sage', 'Мудрец'), ('folk hero', 'Народный герой'), ('hermit', 'Отшельник'), ('pirate', 'Пират'), ('criminal', 'Преступник'), ('soldier', 'Солдат'), ('foreigner', 'Чужеземец'), ('charlatan', 'Шарлатан')], max_length=25, null=True, verbose_name='Предыстория'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Имя персонажа'),
        ),
        migrations.AlterField(
            model_name='character',
            name='experience',
            field=models.IntegerField(default=1, null=True, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)], verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='character',
            name='money',
            field=models.IntegerField(default=12000, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Деньги(медные монеты)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player_name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Имя игрока'),
        ),
        migrations.AlterField(
            model_name='character',
            name='proficiency_bonus',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Бонус мастерства'),
        ),
        migrations.AlterField(
            model_name='character',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='character', to='character.skills', verbose_name='Навыки'),
        ),
        migrations.AlterField(
            model_name='character',
            name='spells',
            field=models.ManyToManyField(null=True, related_name='character', to='character.spells', verbose_name='Заклинания'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(blank=True, null=True, related_name='character', to='character.weapons', verbose_name='Оружие'),
        ),
    ]
