# Generated by Django 5.1 on 2024-12-11 22:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0013_alter_character_money_player_character_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='money',
            field=models.IntegerField(default=12000, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Деньги(медные монеты)'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='character.player'),
        ),
    ]
