# Generated by Django 5.1 on 2025-02-06 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0014_alter_character_money_alter_character_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='max_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='money',
            field=models.IntegerField(default=3000, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Деньги(медные монеты)'),
        ),
    ]
