# Generated by Django 5.1 on 2025-02-06 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0015_character_max_hp_alter_character_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='inventory_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='money',
            field=models.IntegerField(default=6000, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Деньги(медные монеты)'),
        ),
    ]
