# Generated by Django 5.1 on 2025-02-06 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0016_character_inventory_capacity_alter_character_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='money',
            field=models.IntegerField(default=3000, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Деньги(медные монеты)'),
        ),
        migrations.AlterField(
            model_name='race',
            name='speed',
            field=models.IntegerField(verbose_name='Скорость'),
        ),
    ]
