# Generated by Django 5.1 on 2025-03-28 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('character', '0017_alter_character_money_alter_race_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.JSONField(blank=True, null=True, verbose_name='Снаряжение'),
        ),
        migrations.AlterField(
            model_name='character',
            name='money',
            field=models.IntegerField(default=6000, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Деньги(медные монеты)'),
        ),
    ]
